### ISSUE TITLE
Fake leaf and threshold settings producing unwanted artefacts at tips of tree

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#101]
On Safari there is a little bug where the semicircle of a node reverses and bends inwards instead of outwards temporarily whilst something is loading - I think this related to the ‘fake leaf’ code - see attached images (not screen shots but camera pics from pointing at the screen as was hard to catch at the right moment otherwise as it’s related to fake leaves and refresh)… In general I think the code that sets the threshold for detail could probably do with being tweaked as it seems quite sensitive to reducing the detail and then increasing it again which leads to strange artefacts on the tips of the tree - this issue has always been there but somehow now on the Polytomy view it’s worse.

**Comment by jrosindell** [comment]
![2018-06-17 21 54 43](https://user-images.githubusercontent.com/3009279/41512042-9fcfe34e-727a-11e8-8051-0b027664ec9a.jpg)

**Comment by lentinj** [comment]
The above should fix this. The object pool makes it very easy to introduce intermittent bugs of this nature as some of the properties are reset, but not all. Thus the view looks fine until something makes arcs with ``counter_wise`` set to true, at which point the rotation of the half-leaf is dependent on which object it gets out of the pool.

I'm not sure what to do about this class of bugs in general. They're a big time-sink currently, but I'm somewhat nervous that fixing the shapes' release() to reset all properties will introduce bugs in un-noticed parts of OneZoom. Whilst the above is just playing Wac-a-mole, at least I can fix without worrying about all versions of the tree.

**Comment by jrosindell** [comment]
Thanks Jamie, that reason for the bug makes so much sense.  I'm not sure what to do about the more general issue about this part of code being a big time sink.  

Should there be a testing framework on the JS that checks explicitly the functionality of the object pool?  Alternatively replace the object pool with some existing off the shelf framework.  I still find it very strange that the object pool is even needed i.e. the browser should be clever enough do to that kind of thing on its own but apparently it is not!  

You say that you can fix without worry about the other versions of the tree, but isn't this just because you're in branch 3.3 - although the main job is to get OTOP working we do need the final implementation to not break any of the functionality that works currently when we pull it all to the server.

**Comment by lentinj** [comment]
> Should there be a testing framework on the JS that checks explicitly the functionality of the object pool? 

It's not the object pool itself that's at fault, but the shape classes that don't release properly. Yes they could be wrapped in unit-tests that check each parameter is released, but the bigger problem here is what to do if anything is relying on this behaviour (see later).

I think all of this code is living on borrowed time to be honest. The shapes aren't useful abstractions IMO, and a lot of performance is lost generating this very large heap of objects, and in particular sorting them. I think we should be going straight from get_shapes() to rendering on an individual canvas for branch/leaf/signpost. Things like circle_cut_image() give you a more useful level of abstraction for canvas operations, and make it easier to draw all shapes of one type in one go, reducing canvas context switches, which take time.

Having multiple canvases should eradicate the need for height (and thus the sort), and allows the browser to use the GPU for composition. One could also potentially do things like render the full leaves with an SVG/DOM layer instead of canvas, so we get to use regular hover interactions rather than having to recreate our own.

> You say that you can fix without worry about the other versions of the tree, but isn't this just because you're in branch 3.3 - although the main job is to get OTOP working we do need the final implementation to not break any of the functionality that works currently when we pull it all to the server.

Say I fix this by instead forcing ``shape.counter_wise = false`` in release(). This could create a bug in the regular view if, for example, an early arc shape set ``shape.counter_wise = true`` and later shapes relied on recycling these counter_wise arc shapes.

OTOH, forcing a reset in OTOP code won't change any behaviour outside OTOP. Which, given I'm working in OTOP, I should notice.

**Comment by jrosindell** [comment]
Everything you say here makes perfect sense... though it's painful reading. I especially do agree with the multiple layered canvases point - though this is linked to possible WebGL rendering improvements.

I guess fixing this up more generally is outside the scope of the present project but we should discuss how much work it would be to re-organise this part of the codebase to make it more robust. I'll send an e-mail about this....

**Comment by jrosindell** [comment]
One further thought about this.  I agree about rewriting that part of the code to use multiple canvas layers but aside from that I guess that the object pool still gets used in other areas of the code as a valid and necessary optimisation.  To fix this later, could we abstract the release() code for each object to be part of the object pool and have general conventions about release i.e. booleans get set to false numbers to 0 and strings to "" or everything gets set to null.  Another possible convention would be to fix all the parameters in the desired way when objects are taken back out of the pool later

**Comment by jrosindell** [comment]
I was thinking about Jamie's multi canvas layer solution above and how it would end up affecting your SVG export tool?  Wanted to record thoughts here. It would be a shame to use that functionality as I think it's very useful but I fear that it might require everything on one canvas.  A possible solution would be to have a flag on the rendering loop to say draw only layer x on canvas y - hence normal operation proceeds without said flag and one cycle of the render does one frame on all the layers, but if an SVG screenshot is required a canvas is created just for that purpose and render goes through several passes with incrementing layer number each time. This would be inefficient for drawing a frame in dynamic use but still extremely fast for producing of the SVG download.

**Comment by hyanwong** [comment]
Good point about screenshot functionality. Perhaps @lentinj has a good idea for how to retain this? Note that I am using a personal fork of the canvas2svg code (https://github.com/hyanwong/canvas2svg) which properly embeds the jpg files in the svg, rather than using links)

**Comment by lentinj** [comment]
re: screenshots, from what I see canvas2svg provides a mock canvas that records drawing commands and writes relevant SVG XML. We just replace all canvases with C2S objects for a render cycle, then combine the SVG results afterwards. Given the canvases are all the same size, the outputs should be also. SVG layers are even easier, so long as we don't deviate too much from the setup that C2S uses.

Unfortunately a DOM layer won't be an (easy) option, but SVG is closer to what we need anyway.

**Comment by lentinj** [comment]
>  To fix this later, could we abstract the release() code for each object to be part of the object pool and have general conventions about release

A convention will stop it being forgotten, and not really help the situation. I think the least-invasive approach would be to have a common release method that sets all properties of the object to undefined, and then re-run any constructor code.

**Comment by lentinj** [comment]
I'm going to close this since none of the conversation relates to the original bug. But we might want to pull out details into their own place somewhere.
