### ISSUE TITLE
Strange behaviour in links to start exploring

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#231]
If you click on the 'explore birds now' from the front page it takes us to this link life/@=81461.  But the behaviour of the URL is strange and unreliable.  Sometimes we get a nice zoom in as expected, other times we get a zoom out followed by a zoom in in a way that looks a ugly and not expected.  I'm not sure what causes the sporadic incorrect behaviour but suspect it's related to something not being properly loaded before the minimal flight starts

**Comment by jrosindell** [comment]
To clarify what is meant here, the standard flight code always seeks the common ancestor between the target and the screen content - this sometimes results in unnecessary zooming out when the target is already on the screen and just needs to be directly zoomed in on

**Comment by jrosindell** [comment]
I expect that this will also fix 

> bug at start of the tour - first stop slow, it basically moves to the start of the tree when it's already there

**Comment by lentinj** [comment]
From memory: A flight has a start -> ancestor -> end, and a ~smooth arc is performed through the 3 points. An initial flight like this chooses a start node by going up several nodes from the target from the URL. Since it's a parent node, the common ancestor should be the start node, the 3 node flight is skipped, and the flight is just a point-to-point zoom.

A loading race condition seems logical---there's not enough data to do the common ancestor calculation, so is returning a point that's too high up and doing a 3 point zoom needlessly. I'm a bit suspicious that the flight seems to be one of 2 options though. Turning on some debug to see the chosen flight would illuminate matters.

It's tempting to say it's related to #213 (indeed, I'd already typed pretty much my last comment on that ticket), but I'm not convinced it is, since the start and end point should be fixed for an initial flight such as this. OTOH I could be mis-remembering (or there's a bug), and it's not specifying the start node. In which case it's possible it's choosing the wrong one.

**Comment by lentinj** [comment]
Along similar lines, searching for "elephant" and clicking the same elephant multiple times will result in a zoom out-and-in, consistently. Could easily be related.

**Comment by jrosindell** [comment]
I think the race conditions may well be partly responsible here, but there is another potential issue that I actually think is more likely to be responsible....

If we're zooming into a node that's actually on screen already then the code to detect the common ancestor of that node with the current view will search for the common ancestor of everything that's in view.  This will often be a node that's a bit zoomed out rather than a node that's also on screen - so it wants to zoom to that node before zooming into the target node.  

I think instead it needs a more direct check, is the target on screen (or at least, is the target on screen and in the middle part of the screen as right at the edge might be strange) if it is then do a direct zoom, otherwise go via the ancestor.

A second sanity check could be to see that both sections of a 3 point zoom are 'significant' in length - i.e. involve a substantial amount of zooming - if they do not then maybe also skip.

Another thing that I think is going on, a very old bug, is that the jump code doesn't put the tree in precisely the same place as the flight code - this results (I think) in the tiny annoying move we get sometimes where the tree loads and then slowly zooms out a smidge before zooming to the final destination - it's doing a zoom out to the root which isn't precisely the same as a jump to the root - and the jump would be the natural position on the page being freshly loaded.

The race conditions are important, but I suspect harder to test and resolve than the points I've described above.

**Comment by jrosindell** [comment]
Part of this strange behaviour which can easily be replicated is what happens when one clicks on the links to start exploring and then interrupts the flight with a mouse move - in which case it brings up 

"Sorry, the species or group that you asked for is not on the OneZoom tree."

**Comment by lentinj** [comment]
Spot the mistake :)

https://github.com/OneZoom/OZtree/blob/master/OZprivate/rawJS/OZTreeModule/src/controller/controller_anim.js#L247-L249

If the largest visible is a node, it will start finding the common ancestor from the leaf with the matching metacode. When zoomed into elephants, the largest node is one up, whose corresponding leaf is the manatee, so it's jumping back to manatee ancestor and back again.

I can't reproduce the initial birds problem either, and unlike what I said above, it's probably solved with this too. I was wrong above---pzoom leaps to the start node, then zooms out a few steps, then flys to the target from the largest visible node (it used to fly from the start to the target, but that resulted in odd arcs, not straight zooms).

**Comment by jrosindell** [comment]
This solves almost everything from the tests I've just done - but there are two small issues remaining from the text above.

1. the jump code doesn't put the tree in precisely the same place as the flight code - this results (I think) in the tiny annoying move we get sometimes where the tree loads and then slowly zooms out a smidge before zooming to the final destination - it's doing a zoom out to the root which isn't precisely the same as a jump to the root - and the jump would be the natural position on the page being freshly loaded.

2. when one clicks on the links to start exploring and then interrupts the flight with a mouse move - in which case it brings up "Sorry, the species or group that you asked for is not on the OneZoom tree."

Of these 1. is minor but 2. is important for the release and is an example of a problem that does not occur on the currently live site so we've done something to break it.

**Comment by lentinj** [comment]
> when one clicks on the links to start exploring and then interrupts the flight with a mouse move - in which case it brings up "Sorry, the species or group that you asked for is not on the OneZoom tree."

Yup, as expected this is nothing to do with a bad OTT. I've hit this before---the error handling here isn't very refined. 60c8902 will log the actual exception to the console, to prevent future confusion.

What I see is ``Error: Fly is interrupted``. This is here to cancel the promise chain for doing the flight, and isn't actually an error per-se (but there's no separate cancel for JS promises, only error).

Adding ``if (error.message.indexOf("Fly is interrupted") > -1) return true`` to the catch-all error handler in setup_page.js appears to solve the issue, but this is a bit of a bodge. Ideally the error is caught further up and dealt with, in case we're skipping over other setup because of this.

**Comment by lentinj** [comment]
Probably the way forward here is if the bodge above doesn't cause any major problems, commit that and add a lower-priority task to un-knot this properly and handle the error at a point that makes sense.

**Comment by hyanwong** [comment]
OK, this seems a sensible fix for the time being. Thanks. If it's an easy task to un-knot it properly then I think we should see if this can fit into a second day.

**Comment by hyanwong** [comment]
Do you think we should just merge this temporary fix straight into Master @lentinj ?

**Comment by lentinj** [comment]
Seems reasonable, along with cherry-picking 60c8902.

**Comment by hyanwong** [comment]
@lentinj with #324 I've done this in a slightly more principled way, by creating a UserInterruptedError and checking for that. However, it does still give me a `Unhandled Promise Rejection: Error: Fly is interrupted` error in the console, so I guess I'm not quite doing something right. Better than before, though. Discussion at https://github.com/OneZoom/OZtree/issues/325 with my probably poor interpretation of the problem.

**Comment by jrosindell** [comment]
I still get the error on a.onezoom.org repeating as before by clicking on explore links of front page then immediately interrupting the flight.

I think we need Jamie's fix back in.

**Comment by jrosindell** [comment]
Update on the above - I jumped to the wrong conclusion - have tested both solutions here and neither fixes the problem from what I can see.

**Comment by hyanwong** [comment]
Jamie never actually coded a fix - he just put an extra error message in. My one should have solved it, however. Can we move discussion to https://github.com/OneZoom/OZtree/issues/325 if that's the relevant issue?

**Comment by lentinj** [comment]
@hyanwong As part of #535 I stumbled on the problems here. The commit https://github.com/OneZoom/OZtree/commit/ba574cec0322d682d3431e844d150319b89355ec sorts out the imports so instanceof does the right thing.

**Comment by hyanwong** [comment]
Great! Thanks for spotting that. Does this fix the problem in this issue, and if so, can we close it?

**Comment by lentinj** [comment]
Part (2) of https://github.com/OneZoom/OZtree/issues/231#issuecomment-617634742 is certainly done and dusted with this, I don't know about (1), but it's a ~unrelated problem anyway.

**Comment by hyanwong** [comment]
Right, let's close and if necessary open up a new issue if 1. is still bugging us
