### ISSUE TITLE
New Paypal page for renewals

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#304]
Renewals will be slightly different from normal sponsorships, e.g. because multiple items could be renewed at the same time. We probably need a separate paypal page for this. Here's what we noted:

Paypal will need to be parsed the price and a list of OTTIDs together 
 
Paypal should contain enough info on Paypal website that we can recover exactly what the OTTs are for.
 
Item number is important because it’s the thing we can see on the paypal website later in association with a transaction this should be R1234R2345R2345I146576 to give renew (R) and infinite (I) cases for different OTT ids
 
Currently we pass a ‘notify URL’ to paypal for posting 
 
We need to make sure that we don’t allow people to sponsor with a notify string that too long - as this would mean we miss the information needed for the renewal e.g. all OTTids and infinite / normal flags.
 
Max of n (probably 15) at a time and then refresh the page - if they try to do more than 15 then we don’t allow them to submit and give an apologetic message.

**Comment by jrosindell** [comment]
This will be a replacement to the 
pp_process_post.html
page

**Comment by jrosindell** [comment]
This page will also be the first step towards being able to do multiple initial sponsorships in one go.

**Comment by jrosindell** [comment]
This job should also include checking that it works OK.

**Comment by jrosindell** [comment]
#48 might be relevant - not because we're doing this now, but because we anticipate doing it in future and we want the code written to be compatible with this likely future expansion

**Comment by lentinj** [comment]
Notes from meeting:

* There's some initial Paypal research to do here on the number of items possible to hold in a cart, if we have multiple items in one donation cart, or we have one item made up of concatenated OTT ids. This then will feed into any database changes
  * The return path for PayPal to report transactions is possibly old, work out if it needs to be replaced also.
* Alternative option: Generate a random ``PP_transaction_code``, send that to Paypal as the item purchased, and use it to know what to populate when the transaction comes back.
* Need to account for items that haven't expired yet when renewing. Have end_time and number of days, so new renewal entry has a number of days corresponding to the donated amount, and end_time includes any previous sponsorship.

**Comment by lentinj** [comment]
PayPal docs aren't conclusive, but there's more suggestions that multiple ``item_number_(x)`` don't apply to donate forms than suggestions that it'd work—not enough to rely on it I think. Also ``item_number`` fields are 127 chars long, which a bit too restrictive for concatenating IDs. So I think the random ``PP_transaction_code`` is the way. 

My plan here is:

* ``sponsor_renew`` form fields are shaped like a paypal cart
* On submit
    * validate price for selected items
    * Set donor show for given rows
    * Update all rows with a GUID ``PP_transaction_code`` set, prefixed with e.g. "pending:", which is sent to paypal via ``item_number``.
    * Redirect form to paypal using a ``307``.

The Paypal IPN listener can use the interim transaction code to identify rows to update. We also need to update this to match PayPal docs.

**Comment by jrosindell** [comment]
This plan sounds good to me.  A couple of minor thoughts occur.
1.) Do we will support passing OTTID to PayPal for initial sponsorship of a single leaf.
2.) The text passed to PayPal for a basket will need to be considered - for single species it comes up with the name of the species so for multiple species it should probably say 'renewal of x sponsored leaves' or something similar.

**Comment by lentinj** [comment]
> Do we will support passing OTTID to PayPal for initial sponsorship of a single leaf.

Yes, I was going to preserve the existing IPN listener code, and switch on whether it looks OTT-ish or temporary-transaction-code-ish. I think long-term we should use the temporary transaction code for single subscriptions too, but there's no rush, and this ensures a smooth upgrade path.

> The text passed to PayPal for a basket will need to be considered ... 'renewal of x sponsored leaves'

Yes, this is what I was thinking too.

**Comment by lentinj** [comment]
Okay, I've pushed this a bit early to give you both a chance to read through and see what you make of the business logic, but I've seen the paypal loop work at least once :)

There's a few more edge cases to deal with in the renewal form, but I think the bulk of this is there now.

**Comment by lentinj** [comment]
The above moves the guts of sponsorship/reservations from ``OZfunc`` into their own module, and adds unit tests for a good chunk of the functions. There's a few more tests to go, notably:

* Renewing an expired item: This has revealed a hiccup, since to fully copy a row but have it "available" we can't copy ``user_sponsor_name``, which we ideally need to keep around.
* Division of funds with multiple items: Easy enough, however one wrinkle is what to do if funds run out. I think the only way we'd ensure all transactions are noted in MySQL is an extra miscallaneous donations table.

There's notes for running the test at the top. One thing worth noting is that it doesn't try and create a testing database, given most of the database is ~read only I don't think it's worth it. Instead we assume that ``@unittest.example.com`` email addresses and ``UT:...`` basket codes (which aren't possible ordinarily) are fair game and can be destroyed at the start/end of the test, and we keep our changes within this. The unit test can check all the fiddly parts of sponsorship, and then a functional test can just make sure the controller is wired up correctly.

**Comment by lentinj** [comment]
Okay, I think this and #363 are basically there now. The above sorts out the edge cases we talked about, and a few other things I thought of besides.

You can do an end-to-end test if your instance is publicly accessible, so paypal can inform you.

**Comment by jrosindell** [comment]
Maybe this is still not deployed correctly but when I try to go to 

https://www.onezoom.org/sponsor_renew.html

I get

Ticket issued: OZtree/89.215.62.173.2021-11-17.17-22-26.893215f2-16b6-4db9-8c88-04eee9e1f850
(UK time 17:20 ish)

@hyanwong please could you take a look and maybe post the error here.

beyond this, I think it would help to talk through the logic with @lentinj and @hyanwong once Jamie has had the chance to get up to speed with all this again - just to make sure we're all happy with edge cases etc. At that point I'll then renew my own sponsorships as a test and maybe ask some others I know to do the same during the week of the sprint.

**Comment by hyanwong** [comment]
The error is

```
  File "controllers.default.sponsor_renew.py", line 691, in sponsor_renew
KeyError: 'sponsorship_renew_discount'
```

I think that's a bug and it should be simply "sponsorship_config()['renew_discount']" rather than "sponsorship_config()['sponsorship_renew_discount']"

**Comment by hyanwong** [comment]
OK, correcting that works but now I get:

```
  File "modules/sponsorship.py", line 502, in sponsor_renew_hmac_key
    out = myconf.take("sponsorship.hmac_key")
  File "gluon/contrib/appconfig.py", line 90, in take
    (part, '-->'.join(walking)))
BaseException: hmac_key not in config [sponsorship]
```

I guess I need to add the hmac_key: what should I put here @lentinj ?

**Comment by lentinj** [comment]
> I guess I need to add the hmac_key

A random string >10 chars long that's unique to the server.

The request comes from here: https://github.com/OneZoom/OZtree/commit/88b68d5c620b6d22fddae620ecf012fe04edbe8c

We talk about it in here: https://github.com/OneZoom/OZtree/issues/393

**Comment by hyanwong** [comment]
> > I guess I need to add the hmac_key
> 
> A random string >10 chars long that's unique to the server.
> 
> The request comes from here: [88b68d5](https://github.com/OneZoom/OZtree/commit/88b68d5c620b6d22fddae620ecf012fe04edbe8c)
> 
> We talk about it in here: #393

Oh yes, thanks for the reminder @lentinj . Does it need to be the same key on the dev server as on production?

**Comment by lentinj** [comment]
No---it should be unique for every instance. Otherwise the tokens could be shared between dev and prod.

**Comment by hyanwong** [comment]
Thanks. And what characters are allowed - is it upper/lowercase + digits, or basically anything not including spaces. Unicode?

**Comment by hyanwong** [comment]
OK,` hmac_key` set. Now I'm getting:

```
  File "applications/OZtree/compiled/controllers.default.sponsor_renew.py", line 732, in sponsor_renew
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'
```

gradually getting there!

**Comment by hyanwong** [comment]
So it looks like we need to fill out the `sponsorship_ends` field for existing sponsorships. I don't think we do this in the validation page at the moment either. I'd like to remind myself why we created that field - I'm sure there was a good reason.

**Comment by lentinj** [comment]
> what characters are allowed - is it upper/lowercase + digits, or basically anything not including spaces. Unicode?

Anything that doesn't break the config file parser :)

**Comment by lentinj** [comment]
> I'd like to remind myself why we created [sponsorship_ends]

IIRC the idea was to allow things like adding remainder of previous sponsorships, you've got 30 days left, you paid for 4 years (so day count in row is 365 * 4), but ``sponsorship_ends`` is 4y+30d.

There could have been reasons along the lines of delaying sponsorship starts too.

**Comment by lentinj** [comment]
Yup, ``models/db.py`` agrees with my memory:

https://github.com/OneZoom/OZtree/blob/b7a112c67ee6173cc73ada95e4c33c0f629ce738/models/db.py#L569-L572

And yes, looks like ``valid_spons`` doesn't set it as well as any one-off migration. Ideally ``valid_spons`` gets merged with the rest of the sponsorship module, but that's probably too many steps in one go.

**Comment by lentinj** [comment]
Okay, now we set ``sponsorship_ends`` *after* paypal has got back to us. This leaves the repopulation of existing entries in the live DB as the remaining TODO.

**Comment by hyanwong** [comment]
Right - I need to have a one-off SQL command to populate this:

```
update reservations set sponsorship_ends = DATE_ADD(verified_time, INTERVAL sponsorship_duration_days DAY);
```

Then we can actually change some of the code that refers to `sponsorship_duration_days` in the codebase, I think.

**Comment by jrosindell** [comment]
@lentinj please check that the `sponsorship_ends` field is set to the previous `sponsorship_ends` date + `sponsorship_duration_days` rather than using `verified time` which will not be quite the same unless they renew at the last minute.

**Comment by lentinj** [comment]
> @lentinj please check that the sponsorship_ends field is set to the previous sponsorship_ends date + sponsorship_duration_days

https://github.com/OneZoom/OZtree/blob/b7a112c67ee6173cc73ada95e4c33c0f629ce738/modules/sponsorship.py#L183-L195

**Comment by hyanwong** [comment]
Perfect, thanks @lentinj - do you think we should define 365*4+1 up top somewhere for reuse. I assume we use it in other places too.

**Comment by lentinj** [comment]
Done. I was wondering why I didn't meself.
